# Standard Configuration
#
NetworkMode = "reflector"
ReflectorAddress = "cwc0.nodestone.io:7388"
HardwareType = "GPIO"
KeyType = "straight"
SidetoneEnable = true
SidetoneFrequency = 500
RemoteEcho = false
Channel = 0
Callsign = "MYCALL"

# These are BCM numbers, not actual pins
# used for GPIO hardware type
[GPIOPins]
StatusLED = 22
SignalLED = 23
KeyLeft = 17
KeyRight = 27
PWMA = 13
PWMB = 12

# These are signal names
# use for Serial hardware type
[SerialPins]
KeyIn = "CTS"
KeyOut = "RTS"
